import React from 'react';

const Blogs = () => {
    return (
        <div className='mx-10'>
            <h1 className='text-xl font-semibold mb-1'>Q1. How will you improve the performance of a React Application?</h1>
            <p>A. A modern front-end library like React doesn't magically make your app faster. It requires the developer to understand how React works and how the components live through the various phases of the component lifecycle. Memoization is an optimization strategy that caches a component-rendered operation, saves the result in memory, and returns the cached result for the same input. The profiler records how long it takes a component to render, why a component is rendering, and more. From there, we can investigate the affected component and provide the necessary optimization. To successfully optimize our React application, we must first find a performance problem in our application to rectify.</p>
            <h1 className='text-xl font-semibold mt-5 mb-1'>Q2. What are the different ways to manage a state in a React application?</h1>
            <p>A. The state is an object that holds information about a certain component. Plain JavaScript functions don't have the ability to store information. The code within them executes and "dissapears" once the execution is finished. But with the help of react, React functional components can store information even after execution. There are four main types of state you need to properly manage in your React apps. they are: Local state, Global state, Server state and URL state. The state is just a fancy term for a JavaScript data structure. If a user changes state by interacting with your application, the UI may look completely different afterwards, because it's represented by this new state rather than the old state.</p>
            <h1 className='text-xl font-semibold mt-5 mb-1'>Q3. How does prototypical inheritance work?</h1>
            <p>A. JavaScript is a prototype-based, Object Oriented programming language. After the ES6 updates, JavaScript allowed for “prototypal inheritance”, meaning that objects and methods can be shared, extended, and copied. JavaScript is a prototype-based, Object Oriented programming language. After the ES6 updates, JavaScript allowed for “prototypal inheritance”, meaning that objects and methods can be shared, extended, and copied. If we want to read a property of obj or call a method, and it doesn't exist, then JavaScript tries to find it in the prototype.</p>
            <h1 className='text-xl font-semibold mt-5 mb-1'>Q4. What is a unit test? Why should write unit tests?</h1>
            <p>A.  Unit testing is a method that is used to test programs and applications to see if they function according to the clients' specifications. There are two main types of unit testing: manual and automated. The automated method is the most preferred as it is faster and more accurate, but performing this task manually is also an option. The manual approach has a step by step instructional procedure that helps testers perform this task efficiently. The automated unit testing usually involves the developer first writing a section of the code in the application so that the function can be tested. Unit testing has its own importance, and the absence of it might cause problems and can significantly impact the overall performance of the program.</p>
            <h1 className='text-xl font-semibold mt-5 mb-1'>Q5. Why you do not set the state directly in React. For example, if you have const [products, setProducts] = useState([]). Why you do not set products = [...] instead, you use the setProducts?</h1>
            <p>A. useState is a Hook that allows you to have state variables in functional components. You pass the initial state to this function and it returns a variable with the current state value and another function to update this value. Whereas, Destruction is the process of destroying something to its smallest pieces. Array destructuring is a javascript expression that reduces arrays to smaller atoms where the contents of the array can be easily accessed and referenced by variables. So we cannot set products as an array destructuring instead we need to use setProducts.</p>
        </div>
    );
};

export default Blogs;